// Kiosk Global Auto & Idle Management
(function() {
    let idleTimer;
    const IDLE_TIME = 3 * 60 * 1000; // 3 minutes
    
    function resetIdleTimer(isInitial = false) {
        clearTimeout(idleTimer);
        
        // If this reset was triggered by a real user interaction, and we are in auto mode, turn it off.
        if (!isInitial && localStorage.getItem('kiosk_global_auto') === 'true') {
            localStorage.setItem('kiosk_global_auto', 'false');
            console.log('Manual touch detected. Auto mode cancelled.');
            
            // Update Main Menu button if it exists
            const btnAuto = document.getElementById('btn-auto-kiosk');
            if (btnAuto) {
                btnAuto.style.background = "rgba(216, 189, 161, 0.95)";
                btnAuto.style.color = "#121212";
                btnAuto.innerHTML = `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: middle; margin-right: 5px; margin-top: -3px;"><polygon points="5 3 19 12 5 21 5 3"/></svg> Automatic`;
            }
            
            // Update Card 3 Auto button if it exists
            const btnAutoPlay = document.getElementById('btn-autoplay');
            if (btnAutoPlay && typeof isAutoPlayActive !== 'undefined') {
                isAutoPlayActive = false;
                btnAutoPlay.classList.remove('active');
            }
            
            // Dispatch a global event so cards can gracefully stop their own internal logic and audio
            window.dispatchEvent(new Event('kiosk_auto_cancelled'));
        }
        
        // Restart the 3 minute timer
        idleTimer = setTimeout(() => {
            console.log('3 minutes of inactivity. Starting Auto mode.');
            localStorage.setItem('kiosk_global_auto', 'true');
            
            // Route to main menu to initiate random card launch
            if (window.location.pathname.includes('card')) {
                window.location.href = '../index.html';
            } else {
                // If already on main menu, launch directly
                if (typeof window.launchRandomCard === 'function') {
                    window.launchRandomCard();
                } else {
                    window.location.reload();
                }
            }
        }, IDLE_TIME);
    }

    // Listen for manual interactions
    // Use capture phase to ensure we catch it early
    ['mousedown', 'touchstart', 'keydown', 'wheel'].forEach(evt => {
        document.addEventListener(evt, (e) => {
            // Ignore synthetic events generated by our own auto-play scripts (like element.click())
            // isTrusted is true ONLY for real user interactions from physical hardware
            if (e.isTrusted) {
                resetIdleTimer(false);
            }
        }, true);
    });
    
    // Initial start of timer
    resetIdleTimer(true);
})();
